name: yolov3-cpu

dependencies:
  - python<3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - tensorflow==2.0.3
    - protobuf<=3.20.1
    - lxml
    - tqdm
    - seaborn
    - pillow
    - fastapi
    - absl-py
    - uvicorn
    - python-multipart